version: '3'

services:
  app:
    container_name: laravel_app_02
    image: ikasetebo/laravel:angular-1.00
    networks:
      - app_bridge
      - cache
    pid: 'host'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - D:\Repositories\Docker\practice-app\shared:/shared/
      - D:\Repositories\Docker\practice-app\nginx-conf\:/etc/nginx/
      - D:\Repositories\Docker\practice-app\app:/usr/share/nginx/html
      - D:\Repositories\Docker\practice-app\php-conf\fpm\:/etc/php/7.1/fpm/
    depends_on:
      - db
  db:
      container_name: database_02
      image: mysql:8.0
      ports:
        - '3306:3306'
      networks:
        - app_bridge
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_USER=root
  redis:
       container_name: redis_02
       image: redis:3.2.0
       networks:
         - cache
       depends_on:
         - app
  adminer:
        container_name: adminer_02
        image: ikasetebo/adminer:v1.10
        ports:
          - '8080:80'
        networks:
           - app_bridge



networks:
  app_bridge:
    driver: bridge
  cache:
    driver: bridge


